manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: NathanDSanta
      url-base: https://github.com/NathanDSanta
    - name: m165437
      url-base: https://github.com/m165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: chocofi
      remote: NathanDSanta
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
