manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: NathanDSanta
      url-base: https://github.com/NathanDSanta
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nathan-chocofi
      remote: NathanDSanta
      revision: main
  self:
    path: config
